version: '1'
services:
  dashboard:
    container_name: nl-dashboard
    image: nl-dashboard
    platform: linux/x86_64
    ports:
      - 5001:3000
    volumes:
      - ./dashboard:/app
      - /app/node_modules
  backend:
    container_name: nl-backend
    image: nl-backend
    platform: linux/x86_64
    ports:
      - 5002:5000
    volumes:
      - ./backend:/app
  db:
    container_name: nl-db
    image: nl-db
    platform: linux/x86_64
    ports:
      - 5003:3306
    volumes:
      - ./database:/db