version: '0.1'
services: 
  db: 
    image: mysql:5.7
    platform: linux/x86_64
    container_name: db
    restart: always
    env_file:  .env
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports: 
      - ${MYSQL_PORT}:3306
    volumes: 
      - ./db:/var/lib/mysql
  db-workbench: 
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: db-workbench
    restart: always
    env_file:  .env
    environment: 
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      TITLE: Nova Library DB Workbench
      CUSTOM_USER: ${MYSQL_USER}
      CUSTOM_PASSWORD: ${MYSQL_PASSWORD}
    ports: 
      - ${MYSQL_WORKBENCH_PORT}:3000
      - ${MYSQL_WORKBENCH_PORT_SECURE}:3001
    cap_add:
      - IPC_LOCK
    volumes: 
      - ./db:/var/lib/mysql