import { setExistingUserSettings, userSettingsState } from '@/resources/userSettings';
import getTheme from '@/styles/theme';
import CssBaseline from '@mui/material/CssBaseline';
import { ThemeProvider } from '@mui/material/styles';
import type { Metadata } from 'next';
import React, { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const dispatch = useDispatch();
  useEffect(() => {
    const existingSettings = JSON.parse(localStorage.getItem('NL__userSettings') || '');
    if (existingSettings) {
      dispatch(setExistingUserSettings(existingSettings));
    }
  }, []);
  const darkModeState = useSelector((state: userSettingsState) => state.userSettings.darkMode);

  return (
    <ThemeProvider theme={getTheme(darkModeState)}>
      <CssBaseline />
      {children}
    </ThemeProvider>
  );
}
