import { setExistingUserSettings, userSettingsState } from '@/resources/userSettings';
import getTheme from '@/styles/theme';
import { Grid } from '@mui/material';
import CssBaseline from '@mui/material/CssBaseline';
import { ThemeProvider } from '@mui/material/styles';
import type { Metadata } from 'next';
import React, { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import Navbar from './Navbar';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const dispatch = useDispatch();
  useEffect(() => {
    const existingSettings = JSON.parse(localStorage.getItem('NL__userSettings') || '{}');
    if (Object.keys(existingSettings).length > 0) {
      dispatch(setExistingUserSettings(existingSettings));
    }
  }, []);
  const darkModeState = useSelector((state: userSettingsState) => state.userSettings.darkMode);

  return (
    <ThemeProvider theme={getTheme(darkModeState)}>
      <CssBaseline />
      <Grid container spacing={2} sx={{ paddingTop: '1em', height: '100%' }}>
        <Grid item xs={1}>
          <Navbar />
        </Grid>
        <Grid item xs={11}>
          <main style={{ flexShrink: 0, flexGrow: 1, margin: '0 1em' }}>{children}</main>
        </Grid>
      </Grid>
    </ThemeProvider>
  );
}
